import Head from "next/head";
import '@fortawesome/fontawesome-free/css/all.min.css';
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-wf-page="66095c4f9765fb9eae51e7eb" data-wf-site="">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        {children}

     
      </body>
    </html>
  );
}
